refactor(web-client): add inputs to profile card
ntls-io/nautilus-wallet pull request #138
Opened 2021-11-27 09:54 UTC by jongbonga

2022-03-11 10:42 UTC, longtomjr approved these changes

2022-03-11 10:57 UTC, PiDelport requested changes
There's a Storybook story that needs parameters, which should a be a quick fix: I made a Chromatic comment.

Looks good otherwise!

2022-03-14 14:12 UTC, PiDelport approved these changes

2022-03-14 14:13 UTC, PiDelport commented
Looks good! 🎉

2022-03-14 15:11 UTC, merged