[WIP] feat-initial-wallet-enclave-sessions
ntls-io/nautilus-wallet pull request #351
Opened 2022-09-05 06:56 UTC by jdvlio

### Overview

Certain multi-step wallet operations require that two or more messages related messages be sent for processing by the enclave.   Since the enclave has no built-in means of verifying that such messages are indeed from the same source, a cryptographic mechanism is necessary to essentially establish "sessions" across such messages.

### Aim
 
Provide a simple, albeit rudimentary, solution to the aforementioned problem through the use of a combination of a Diffie-Hellman key exchange and session keys deterministically generated by the enclave.

### Context

The need for this functionality arose in the context of PR #324, where authentication details need to be verified prior to a follow-up message that contains the new to-be PIN for the user wallet.  The enclave needs some mechanism by which it can verify that the latter message originates from the same source as the former containing the user responses to pre-defined security questions.

2022-09-08 11:37 UTC, jongbonga commented on web-client/src/schema/session.ts
> +    let hmac = new HMAC(SHA256, this.secret);
```suggestion
    const hmac = new HMAC(SHA256, this.secret);
```

2022-09-08 13:37 UTC, billguo99 requested changes

2022-09-08 13:37 UTC, billguo99 commented on web-client/src/schema/crypto.ts
> +  constructor(public keyPair: BoxKeyPair) { }
npm run format

2022-09-12 14:35 UTC, billguo99 approved these changes

2022-09-15 11:59 UTC, merged